import React from 'react';
import type { Memory } from '../../types';
import { Database, X } from 'lucide-react';

interface Props {
  memories: Memory[];
  onClose: () => void;
}

export const MemorySourceDrawer: React.FC<Props> = ({ memories, onClose }) => {
  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-xs flex items-center justify-center p-4 z-50">
      <div className="bg-[var(--color-bg-surface)] border border-[var(--color-border)] rounded-2xl p-6 max-w-xl w-full max-h-[85vh] flex flex-col shadow-2xl">
        <div className="flex items-center justify-between pb-4 border-b border-[var(--color-border-subtle)]">
          <div className="flex items-center gap-2">
            <Database className="w-4 h-4 text-[var(--color-accent)]" />
            <h3 className="text-lg font-heading font-semibold text-[var(--color-text-main)]">
              Grounded Memory Sources ({memories.length})
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg border border-[var(--color-border)] hover:bg-[var(--color-bg-elevated)] text-[var(--color-text-muted)] cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto py-4 space-y-4">
          <p className="text-xs text-[var(--color-text-muted)] font-body">
            The AI response was generated by retrieving and reasoning over the following verified organizational memories from Hindsight:
          </p>

          {memories.map((mem, index) => (
            <div
              key={mem.id || index}
              className="p-4 rounded-xl border border-[var(--color-border)] bg-[var(--color-bg-base)] space-y-2 text-xs"
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="font-mono font-semibold px-2 py-0.5 rounded bg-[var(--color-accent-subtle)] text-[var(--color-accent)] border border-[var(--color-accent-border)] text-[10px]">
                    {mem.department}
                  </span>
                  <span className="font-mono font-bold text-[var(--color-text-main)] text-[11px]">
                    Entity: {mem.entity}
                  </span>
                </div>
                <div className="flex items-center gap-2 font-mono text-[10px] text-[var(--color-text-subtle)]">
                  <span>{mem.date}</span>
                  <span className="text-emerald-600 dark:text-emerald-400">
                    {(mem.confidence * 100).toFixed(0)}% Conf
                  </span>
                </div>
              </div>

              <p className="font-heading text-sm text-[var(--color-text-main)] leading-snug">
                "{mem.observation}"
              </p>

              <div className="p-2.5 rounded bg-[var(--color-bg-surface)] border border-[var(--color-border-subtle)] font-body text-[var(--color-text-muted)]">
                <strong className="text-[var(--color-text-main)]">Evidence: </strong>
                {mem.evidence}
              </div>

              {mem.historicalAction && (
                <div className="text-[11px] text-[var(--color-text-subtle)] font-body italic pt-1 border-t border-[var(--color-border-subtle)]">
                  Action taken: {mem.historicalAction} {mem.outcome && `(${mem.outcome})`}
                </div>
              )}
            </div>
          ))}
        </div>

        <div className="pt-3 border-t border-[var(--color-border-subtle)] flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-1.5 text-xs rounded-lg bg-[var(--color-text-main)] text-[var(--color-bg-base)] font-medium cursor-pointer"
          >
            Close Sources
          </button>
        </div>
      </div>
    </div>
  );
};
